#!/usr/bin/env sh
cd /Users/denismorand/Documents/Developement/AdeleResearchGroup/Cilia/examples/si-example/gateway/target/distrib-temp
exec java -Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=y -jar bin/felix.jar
